services:
  - type: web
    name: syncruncode-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        fromDatabase:
          name: syncruncode-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRE
        value: 7d
      - key: CORS_ORIGIN
        value: https://syncruncode.vercel.app
      - key: RATE_LIMIT_WINDOW_MS
        value: 900000
      - key: RATE_LIMIT_MAX_REQUESTS
        value: 100
      - key: EXECUTION_TIMEOUT
        value: 5000
      - key: MAX_FILE_SIZE
        value: 10485760

databases:
  - name: syncruncode-db
    plan: starter
    databaseName: syncruncode
